<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestingDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bca686eb-9768-4516-a7fe-7dc98056d0d0</testSuiteGuid>
   <testCaseLink>
      <guid>31053d05-2661-4566-b935-421de14513a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>197f71bc-ae5f-4bb6-9975-dc236c3949df</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>197f71bc-ae5f-4bb6-9975-dc236c3949df</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>53cad414-735d-4588-9bf2-81f9be5265b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>197f71bc-ae5f-4bb6-9975-dc236c3949df</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fbb58512-2d02-4004-a1b8-3722b6ba3901</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
